### ISSUE TITLE
SPM support broken?

### ISSUE THREAD

**Issue by nmtitov** [TelegramMessenger/TelegramStickersImport#1]
When installing via SPM I get the following error:

```
/Package.swift has no Package.swift manifest for version 1.0.0 in https://github.com/TelegramMessenger/TelegramStickersImport
```

Looks like `Package.swift` is missing?

**Comment by otopba** [comment]
Fixed at https://github.com/TelegramMessenger/TelegramStickersImport/pull/3/files?file-filters%5B%5D=.swift
