### ISSUE TITLE
Check emojis are present

### ISSUE THREAD

**Issue by nikstar** [TelegramMessenger/TelegramStickersImport#5]
Currently, if emoji is missing, sticker set is sent to Telegram.app without raising an error. Telegram doesn't show any error either, but import is stuck at 100% indefinitely.

If emojis array is empty for a sticker, `addSticker(data:, emoji:)` should raise an error.

**Comment by sashkyn** [comment]
+

**Comment by laktyushin** [comment]
Fixed in 1.1.0, thanks.
