### ISSUE TITLE
Не работает экспорт в телеграм анимированных стикеров.

### ISSUE THREAD

**Issue by stayf** [TelegramMessenger/TelegramStickersImport#8]
Добрый день. Критичный баг с экспортом в телеграм. 
Устройство iphone SE(первое поколение) ios 14.8. На других устройствах не смотрел.
Если экспортировать стикеры(анимированные) в телеграм, а мобильное приложение телеграма было не запущено ранее, то в телеграме невозможно произвести экспорт(отображается два меню с экспортом и при создании ссылки вечно крутится троббер). При повторной попытке экспортировать при уже запущенном телеграме все работает корректно. Прикладываю видео. Воспроизвести баг можно [тут](https://apps.apple.com/app/id1575123344)

https://user-images.githubusercontent.com/1859216/138050951-cc00a5f2-0217-4bbb-b454-9b2f744654a4.mp4

**Comment by laktyushin** [comment]
Fixed in 8.5.1
